import 'package:ecommerce_app/src/domain/product.dart';

const kTestProducts = [
  Product(
    id: '1',
    name: 'Bruschetta plate',
    imageUrl: 'assets/products/bruschetta-plate.jpg',
    price: 15,
    stockQuantity: 5,
  ),
  Product(
    id: '2',
    name: 'Mozzarella plate',
    imageUrl: 'assets/products/mozzarella-plate.jpg',
    price: 13,
    stockQuantity: 5,
  ),
  Product(
    id: '3',
    name: 'Pasta plate',
    imageUrl: 'assets/products/pasta-plate.jpg',
    price: 17,
    stockQuantity: 5,
  ),
  Product(
    id: '4',
    name: 'Piggy Bank Blue',
    imageUrl: 'assets/products/piggy-blue.jpg',
    price: 12,
    stockQuantity: 5,
  ),
  Product(
    id: '5',
    name: 'Piggy Bank Green',
    imageUrl: 'assets/products/piggy-green.jpg',
    price: 12,
    stockQuantity: 10,
  ),
  Product(
    id: '6',
    name: 'Piggy Bank Pink',
    imageUrl: 'assets/products/piggy-pink.jpg',
    price: 12,
    stockQuantity: 10,
  ),
  Product(
    id: '7',
    name: 'Pizza plate',
    imageUrl: 'assets/products/pizza-plate.jpg',
    price: 18,
    stockQuantity: 10,
  ),
  Product(
    id: '8',
    name: 'Plate and Bowl',
    imageUrl: 'assets/products/plate-and-bowl.jpg',
    price: 21,
    stockQuantity: 10,
  ),
  Product(
    id: '9',
    name: 'Salt and pepper lemon',
    imageUrl: 'assets/products/salt-pepper-lemon.jpg',
    price: 11,
    stockQuantity: 10,
  ),
  Product(
    id: '10',
    name: 'Salt and pepper olives',
    imageUrl: 'assets/products/salt-pepper-olives.jpg',
    price: 11,
    stockQuantity: 10,
  ),
  Product(
    id: '11',
    name: 'Snacks plate',
    imageUrl: 'assets/products/snacks-plate.jpg',
    price: 24,
    stockQuantity: 10,
  ),
  Product(
    id: '12',
    name: 'Flowers plate',
    imageUrl: 'assets/products/flowers-plate.jpg',
    price: 22,
    stockQuantity: 10,
  ),
  Product(
    id: '13',
    name: 'Juicer for citrus fruits',
    imageUrl: 'assets/products/juicer-citrus-fruits.jpg',
    price: 14,
    stockQuantity: 10,
  ),
  Product(
    id: '14',
    name: 'Honey pot',
    imageUrl: 'assets/products/honey-pot.jpg',
    price: 16,
    stockQuantity: 10,
  ),
];
